version: 2.1

commands:
  "system-dependencies":
    description: "Install required packages"
    steps:
      - run: apt-get -yqq update
      - run: apt-get -yqq install git unzip zip
      - run: curl -sS https://getcomposer.org/installer | php
      - run: chmod +x composer.phar
      - run: mv composer.phar /usr/local/bin/composer

executors:
  "php-7-3":
    docker:
      - image: php:7.3
    working_directory: ~/repo_php_7_3
  "php-7-4":
    docker:
      - image: php:7.4
    working_directory: ~/repo_php_7_4

aliases:
  - &composer_7_3_cache_key
    composer-7.3-{{ checksum "composer.lock" }}
  - &wd_7_3
    ~/repo_php_7_3
  - &composer_7_4_cache_key
    composer-7.4-{{ checksum "composer.lock" }}
  - &wd_7_4
    ~/repo_php_7_4
  - &ignore_non_dev_branches
    filters:
      tags:
        only: /.*/
      branches:
        ignore:
          - gh-pages
          - l10n_master
          - /release\/.*/

jobs:
  prepare_7_3:
    executor: "php-7-3"
    steps:
      - checkout
      - "system-dependencies"
      - restore_cache:
          key: *composer_7_3_cache_key
      - run: composer install --no-progress
      - save_cache:
          key: *composer_7_3_cache_key
          paths:
            - vendor/
      - persist_to_workspace:
          root: *wd_7_3
          paths:
            - ./*

  test_7_3:
    executor: "php-7-3"
    steps:
      - checkout
      - "system-dependencies"
      - attach_workspace:
          at: *wd_7_3
      - run: php ./bin/phpbin php:lint
      
  prepare_7_4:
    executor: "php-7-4"
    steps:
      - checkout
      - "system-dependencies"
      - restore_cache:
          key: *composer_7_4_cache_key
      - run: composer install --no-progress
      - save_cache:
          key: *composer_7_4_cache_key
          paths:
            - vendor/
      - persist_to_workspace:
          root: *wd_7_4
          paths:
            - ./*

  test_7_4:
    executor: "php-7-4"
    steps:
      - checkout
      - "system-dependencies"
      - attach_workspace:
          at: *wd_7_4
      - run: php ./bin/phpbin php:lint

  code_checks:
    executor: "php-7-4"
    steps:
      - checkout
      - "system-dependencies"
      - attach_workspace:
          at: *wd_7_4
      - run: php ./bin/phpbin php:style
      - run: php ./bin/phpbin php:metrics
      - store_artifacts:
          path: build/metrics
          destination: metrics



workflows:
  version: 2
  php_versions:
    jobs:
      - prepare_7_3:
          <<: *ignore_non_dev_branches
      - test_7_3:
          requires:
            - prepare_7_3
          <<: *ignore_non_dev_branches
      - prepare_7_4:
          <<: *ignore_non_dev_branches
      - test_7_4:
          requires:
            - prepare_7_4
          <<: *ignore_non_dev_branches
  code_quality:
    jobs:
      - prepare_7_4:
          <<: *ignore_non_dev_branches
      - code_checks:
          requires:
            - prepare_7_4
          <<: *ignore_non_dev_branches
